# conn_stride2_assign_claude.py
# Chunk 1 of conn_stride2_three_site_impl_plan_claude.md: build the three-site assignment table for
# the stride-2 completion of the connected local-current Y_lm tower.
#
# PARTITION RULE (NM 2026-08-10, Q2 = "hybrid: job by offset, machine by ensemble"):
#   - the MACHINE is chosen per ENSEMBLE -- all four offsets of an ensemble go to the same site, so
#     that site needs only that ensemble's configs and the ensemble always ends up complete at
#     stride 2 no matter which site is slower;
#   - the JOB is one (ensemble, offset) unit -- the four offsets are the intra-site parallelism.
#
# WHY FOUR OFFSETS: existing conn data sits on k = first + 10 j (stride-10 grid, first = 1 everywhere).
# The stride-2 target grid is k = first + 2 j.  The difference is exactly the four residue classes
# k = first + {2,4,6,8} + 10 j, i.e. --kmin first+off --stride 10 for off = 2,4,6,8.  Disjoint from the
# existing data by construction, so no already-solved h5 is ever shipped or recomputed.
#
# COST MODEL: measured per-config wall time from the "[... s]" markers the driver prints, harvested
# from conn_L*_g*_Nf*_w*_claude.log (8992 configs, 2-proc/GPU MPS packing on TITAN V).  Two L3 Nf6
# ensembles were never measured (they appeared after the stride-10 run started); they borrow the L3 Nf4
# value at the same gsq.  These are TITAN V seconds -- FNAL/SCC need the Chunk-2 calibration factor.
#
# Writes:  conn_stride2_assign_claude.txt        (authoritative table, one line per unit)
#          conn_stride2_cmds_fnal_claude.txt     (FNAL deliverable per Q4: literal command lines)
import glob
import re
import numpy as np

# ---- Q7 knob: relative capacity share per site.  Default = equal thirds. ----
WEIGHTS = {"LOCAL": 1.0, "FNAL": 1.0, "SCC": 1.0}

OFFSETS = [2, 4, 6, 8]
GRID_STRIDE = 10           # sub-stream stride; 4 offsets x stride 10 = the stride-2 grid
LAT_BYTES = {1: 43008, 2: 165888, 3: 370688, 4: 657408}
H5_BYTES = 700456          # conn h5 is the same size at every L (set by Nt and the l<=3 tower)


def measured_time_per_config():
    t = {}
    for fn in glob.glob("conn_L*_g*_Nf*_w*_claude.log"):
        m = re.match(r"conn_L(\d)_g([0-9.]+)_Nf(\d)_w(\d)_claude\.log", fn)
        if not m:
            continue
        key = (int(m.group(1)), int(m.group(3)), float(m.group(2)))
        for line in open(fn, errors="ignore"):
            mm = re.search(r"hit 1 done \(conn.*?\[([0-9.e+-]+) s\]", line)
            if mm:
                t.setdefault(key, []).append(float(mm.group(1)))
    for key in t:
        t[key] = float(np.mean(t[key]))
    # never-measured L3 Nf6 ensembles borrow L3 Nf4 at the same gsq
    for g in (3.0, 4.5):
        if (3, 6, g) not in t and (3, 4, g) in t:
            t[(3, 6, g)] = t[(3, 4, g)]
    return t


tsec = measured_time_per_config()

ens = []
for d in sorted(glob.glob("Nf*mRe0.000000*nt128L*_hb*/")):
    name = d.rstrip("/")
    L = int(re.search(r"nt128L(\d+)", name).group(1))
    nf = int(re.search(r"Nf(\d+)", name).group(1))
    g = float(re.search(r"gsq([0-9.]+)at", name).group(1))
    at = float(re.search(r"at([0-9.]+)nu0", name).group(1))
    ks = sorted(int(x.split(".")[-1]) for x in glob.glob(d + "ckpoint_lat.*")
                if x.split(".")[-1].isdigit())
    first = ks[0]
    last = ks[-1]
    t = tsec[(L, nf, g)]
    n_per_off = len(range(first + OFFSETS[0], last + 1, GRID_STRIDE))
    cost = 4 * n_per_off * t / 3600.0
    ens.append(dict(name=name, L=L, nf=nf, g=g, at=at, first=first, last=last,
                    nlat=len(ks), t=t, n_per_off=n_per_off, cost=cost))

# ---- balanced greedy partition of WHOLE ensembles by worker-h ----
total = sum(e["cost"] for e in ens)
wsum = sum(WEIGHTS.values())
target = {s: total * w / wsum for s, w in WEIGHTS.items()}
load = {s: 0.0 for s in WEIGHTS}
for e in sorted(ens, key=lambda x: -x["cost"]):
    site = max(WEIGHTS, key=lambda s: target[s] - load[s])
    e["site"] = site
    load[site] += e["cost"]

# ---- authoritative table ----
out = []
out.append("# conn_stride2_assign_claude.txt -- three-site assignment for the stride-2 conn completion")
out.append("# generated by conn_stride2_assign_claude.py; see conn_stride2_three_site_impl_plan_claude.md")
out.append("#")
out.append("# MACHINE is per ENSEMBLE (all 4 offsets of an ensemble stay on one site); JOB is one")
out.append("# (ensemble, offset) unit.  The 4 offsets are disjoint from the existing stride-10 data.")
out.append("# Run a unit with:")
out.append("#   ./jj_local_ylm_scalar_conn_stoch_L<L>.o --gsq <gsq> --Nf <Nf> --nu0 1.0 \\")
out.append("#       --ens-dir <ensemble>/ --kmin <kmin> --stride <stride> --kmax <kmax> \\")
out.append("#       --nhits 1 --t0 0 --spin-dilution")
out.append("# kmax is last+1 AT GENERATION TIME; L3/L4 are still growing, so regenerate and re-run")
out.append("# after each config top-up (finished configs are skipped via the h5 'complete' gate).")
out.append("#")
out.append("# columns: ensemble L Nf gsq at offset kmin stride kmax ncfg site worker_h")
for e in sorted(ens, key=lambda x: (x["site"], x["L"], x["g"], x["nf"], x["at"])):
    for off in OFFSETS:
        kmin = e["first"] + off
        kmax = e["last"] + 1
        n = len(range(kmin, kmax, GRID_STRIDE))
        out.append("%s %d %d %.6f %.6f %d %d %d %d %d %s %.1f"
                   % (e["name"], e["L"], e["nf"], e["g"], e["at"], off, kmin, GRID_STRIDE,
                      kmax, n, e["site"], n * e["t"] / 3600.0))
open("conn_stride2_assign_claude.txt", "w").write("\n".join(out) + "\n")

# ---- FNAL deliverable: literal command lines only (Q4: no batch script from Claude) ----
cmds = []
cmds.append("# conn_stride2_cmds_fnal_claude.txt -- FNAL units, literal command lines (Q4).")
cmds.append("# Run from the production dir; binaries built per L with -DN_REFINE_CLI=<L>.")
cmds.append("# Each line is one independent job; the 4 offsets of an ensemble may run concurrently.")
for e in sorted(ens, key=lambda x: (x["L"], x["g"], x["nf"], x["at"])):
    if e["site"] != "FNAL":
        continue
    for off in OFFSETS:
        cmds.append("./jj_local_ylm_scalar_conn_stoch_L%d.o --gsq %.6f --Nf %d --nu0 1.0 "
                    "--ens-dir %s/ --kmin %d --stride %d --kmax %d --nhits 1 --t0 0 --spin-dilution"
                    % (e["L"], e["g"], e["nf"], e["name"], e["first"] + off, GRID_STRIDE, e["last"] + 1))
open("conn_stride2_cmds_fnal_claude.txt", "w").write("\n".join(cmds) + "\n")

# ---- summary ----
print("total stride-2 completion = %.0f worker-h, %d configs, %d units"
      % (total, sum(4 * e["n_per_off"] for e in ens), 4 * len(ens)))
print()
print("%-6s %5s %10s %8s %12s %12s" % ("site", "nens", "worker-h", "share", "configs out", "h5 back"))
for s in sorted(WEIGHTS):
    sel = [e for e in ens if e["site"] == s]
    cfg_bytes = sum(e["nlat"] * LAT_BYTES[e["L"]] for e in sel)
    h5_bytes = sum(4 * e["n_per_off"] for e in sel) * H5_BYTES
    print("%-6s %5d %10.0f %7.1f%% %10.1f GB %10.1f GB"
          % (s, len(sel), load[s], 100 * load[s] / total, cfg_bytes / 1e9, h5_bytes / 1e9))
print()
for s in sorted(WEIGHTS):
    sel = sorted([e for e in ens if e["site"] == s], key=lambda x: (x["L"], x["g"], x["nf"], x["at"]))
    print("%s:" % s)
    for e in sel:
        print("   L%d Nf%d g%-4.1f at%.1f  %4d cfg/offset  %6.1f worker-h"
              % (e["L"], e["nf"], e["g"], e["at"], e["n_per_off"], e["cost"]))
print()
print("# wrote conn_stride2_assign_claude.txt (%d unit lines)" % (4 * len(ens)))
print("# wrote conn_stride2_cmds_fnal_claude.txt")
