#!/usr/bin/env python3
# icos_harmonics_claude.py  -- icosahedral-invariant spherical harmonics J_l on the QFE S2 mesh.
# The lattice symmetry is the icosahedral rotation group I (order 60, ~ A5).  The trivial (A) irrep
# subduces from SO(3) rep l at l = 0, 6, 10, 12, ...  For those l there is (for l=6,10,12) a UNIQUE
# icosahedrally-invariant combination J_l(x) = sum_m a_m Y_lm(x); it is the lowest orbital excitation
# that "mixes with l=0" in the 0++ (A) channel and gives a new single-meson interpolator sigma_{J_l}.
#
# Construction (frame-native, no Wigner D):
#   1. the 12 icosahedron vertices are the L=1 mesh sites (pts_n1.dat) -> build the 60 rotations in the
#      mesh frame by closing the group generated by 72 deg rotations about the vertex axes.
#   2. each rotation permutes the mesh sites: pi_g(i) = argmin_j |R x_i - x_j|.
#   3. real Y_l basis at the sites -> P_A = mean_g pinv(Yl) @ Yl[pi_g] projects onto the invariant;
#      its eigenvalue-1 eigenvector is a, and J_l = Yl @ a (verified constant on group orbits).
# Reference: standard SO(3) -> I subduction (e.g. Altmann-Herzig); Peardon 0905.2160 for distillation.

import os
os.environ.setdefault("OMP_NUM_THREADS", "4")
import numpy as np
from scipy.special import sph_harm_y


def load_vec3(path):
    out = []
    with open(path) as f:
        for line in f:
            s = line.split()
            if len(s) < 3:
                continue
            out.append([float(s[0]), float(s[1]), float(s[2])])
    return np.array(out)


def rot_axis(axis, ang):
    # Rodrigues rotation matrix about unit axis by angle ang
    u = axis / np.linalg.norm(axis)
    c = np.cos(ang)
    s = np.sin(ang)
    K = np.array([[0.0, -u[2], u[1]], [u[2], 0.0, -u[0]], [-u[1], u[0], 0.0]])
    return c * np.eye(3) + s * K + (1.0 - c) * np.outer(u, u)


def icosahedral_rotations(verts):
    # close the group generated by 72 deg rotations about each vertex axis (frame = verts)
    gens = []
    for v in verts:
        gens.append(rot_axis(v, 2.0 * np.pi / 5.0))
    group = [np.eye(3)]
    keys = {tuple(np.round(np.eye(3).ravel(), 5))}
    changed = True
    while changed:
        changed = False
        for g in list(group):
            for h in gens:
                m = g @ h
                k = tuple(np.round(m.ravel(), 5))
                if k not in keys:
                    keys.add(k)
                    group.append(m)
                    changed = True
    return group


def site_perms(sites, rots):
    perms = []
    for R in rots:
        rx = sites @ R.T                              # rotated site coords
        d2 = ((rx[:, None, :] - sites[None, :, :]) ** 2).sum(-1)
        pi = np.argmin(d2, axis=1)
        res = np.sqrt(d2[np.arange(len(sites)), pi]).max()
        assert len(set(pi.tolist())) == len(sites), "rotation is not a site permutation"
        assert res < 1e-6, "site match residual too large: %.2e" % res
        perms.append(pi)
    return perms


def real_Yl(sites, l):
    # real basis of the degree-l harmonic space evaluated at the sites: 2l+1 columns
    x = sites[:, 0]
    y = sites[:, 1]
    z = sites[:, 2]
    r = np.sqrt((sites ** 2).sum(1))
    theta = np.arccos(np.clip(z / r, -1.0, 1.0))
    phi = np.arctan2(y, x)
    cols = [sph_harm_y(l, 0, theta, phi).real]
    for m in range(1, l + 1):
        Ym = sph_harm_y(l, m, theta, phi)
        cols.append(np.sqrt(2.0) * Ym.real)
        cols.append(np.sqrt(2.0) * Ym.imag)
    return np.array(cols).T                           # (N, 2l+1)


def invariant_harmonic(sites, l, perms, tol=1e-6):
    # returns (J_l values on sites, n_invariants).  J is L2-normalized on the mesh (sum J^2 = 1).
    # NOTE: projecting on the coarse mesh aliases high l (only #orbits invariants exist on the mesh).
    # Prefer invariant_coeffs (clean, fine group-orbit grid) + Jl_on_sites for the continuum harmonic.
    Yl = real_Yl(sites, l)
    pinv = np.linalg.pinv(Yl)
    PA = np.zeros((Yl.shape[1], Yl.shape[1]))
    for pi in perms:
        PA += pinv @ Yl[pi]
    PA /= len(perms)
    w, Vv = np.linalg.eig(PA)
    inv = [i for i in range(len(w)) if abs(w[i].real - 1.0) < 1e-4 and abs(w[i].imag) < 1e-6]
    n_inv = len(inv)
    if n_inv == 0:
        return np.zeros(len(sites)), 0
    a = Vv[:, inv[0]].real
    J = Yl @ a
    J = J / np.sqrt((J ** 2).sum())
    return J, n_inv


def invariant_coeffs(l, rots, seed=0):
    # clean continuum icosahedral-invariant coefficient vector a (real-Y_l basis, length 2l+1),
    # found on a fine GROUP-ORBIT grid (closed under the group) so there is no mesh aliasing.
    rng = np.random.default_rng(seed)
    seeds = rng.standard_normal((5, 3))
    seeds = seeds / np.linalg.norm(seeds, axis=1, keepdims=True)
    grid = np.vstack([s @ R.T for R in rots for s in seeds])   # full orbit of the seeds -> group-closed
    d2 = ((grid[:, None, :] - grid[None, :, :]) ** 2).sum(-1)
    Yl = real_Yl(grid, l)
    pinv = np.linalg.pinv(Yl)
    PA = np.zeros((Yl.shape[1], Yl.shape[1]))
    for R in rots:
        rg = grid @ R.T
        dd = ((rg[:, None, :] - grid[None, :, :]) ** 2).sum(-1)
        pi = np.argmin(dd, axis=1)
        PA += pinv @ Yl[pi]
    PA /= len(rots)
    w, Vv = np.linalg.eig(PA)
    inv = [i for i in range(len(w)) if abs(w[i].real - 1.0) < 1e-4 and abs(w[i].imag) < 1e-6]
    if not inv:
        return None
    return Vv[:, inv[0]].real


def Jl_on_sites(sites, l, rots, seed=0):
    # continuum icosahedral harmonic J_l sampled at the mesh sites (mean 0 for l>0, unit L2 on sites)
    a = invariant_coeffs(l, rots, seed)
    if a is None:
        return None
    J = real_Yl(sites, l) @ a
    J = J - J.mean() if l == 0 else J
    n = np.sqrt((J ** 2).sum())
    return J / n if n > 0 else J


def build(geom_dir, L):
    verts = load_vec3(geom_dir + "pts_n1.dat")        # 12 icosahedron vertices (mesh frame)
    verts = verts / np.linalg.norm(verts, axis=1, keepdims=True)
    rots = icosahedral_rotations(verts)
    sites = load_vec3(geom_dir + "pts_n%d.dat" % L)
    sites = sites / np.linalg.norm(sites, axis=1, keepdims=True)
    perms = site_perms(sites, rots)
    return sites, rots, perms


if __name__ == "__main__":
    import sys
    GEOM = "../../geometry/data/"
    L = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    sites, rots, perms = build(GEOM, L)
    print("# L=%d  N_sites=%d  |group|=%d (expect 60)" % (L, len(sites), len(rots)))
    print("#  l   n_invariant   max|J[pi_g]-J| (invariance check)")
    for l in range(0, 13):
        J, ninv = invariant_harmonic(sites, l, perms)
        if ninv > 0:
            dev = max(np.abs(J[pi] - J).max() for pi in perms)
        else:
            dev = 0.0
        flag = "  <== A irrep" if ninv > 0 and l > 0 else ("  (l=0 trivial)" if l == 0 else "")
        print("  %2d   %d            %.2e%s" % (l, ninv, dev, flag))
