#!/usr/bin/env bash
# run_distill_L1_mrhs_claude.sh -- L1 perambulator sweep using the MRHS driver (distill_peram_mrhs_claude.cu),
# ~2.5x faster than _v1 (validated: T2a 6.7e-7, mrhs 180 s vs single 450 s).  --nsrc 1 (single source window):
# the h5 is BYTE-IDENTICAL to _v1, and --out-suffix "" MERGES into the production distill_Nv24/ (the driver's
# skip-if-/peram/tau guard protects the configs already generated by _v1 -> NEVER overwrites).  So this just
# COMPLETES the remaining L1 configs (e.g. Nf6 gsq1.0 260 left, gsq1.5) into the existing dataset.
#
# GPU1, MPS NPACK=2, sub-stream tiling like the _v1 sweep.  RESUMABLE, skip-protected.  NO rm.  NO kill.
# Launch DETACHED:  setsid nohup bash run_distill_L1_mrhs_claude.sh > /dev/null 2>&1 < /dev/null &
# Per-worker log -> distill_L1_mrhs_w<WID>_claude.log .  RUN ONLY after the _v1 sweep is stopped (frees GPU1).
set -u
cd /mnt/barracuda22/qed3/qed3/src/production || exit 1

# ---- knobs ----
GPU="${GPU:-1}"
NPACK="${NPACK:-2}"
STRIDE="${STRIDE:-10}"
NV=24                  # full 2*N_SITES at L1 (exact local)
TSRC0=0
TWIN=32
AT_TOKEN="${AT_TOKEN:-at0.200000}"
L=1
ENS_GLOB="${ENS_GLOB:-Nf*_gsq*${AT_TOKEN}*mRe0.000000mIm0.000000nt128L${L}_hb*}"

NVCC=/usr/local/cuda-12.6/bin/nvcc
NVCCFLAGS="-w -arch=sm_70 -O3 -std=c++20 -lcublas -lcusolver -lcusparse -lgomp -Xcompiler -fopenmp"
H5I="-I/mnt/hdd_barracuda/opt/highfive/include/ -I/mnt/hdd_barracuda/opt/myhdfstuff/hdf5-2.1.0/include/"
INCLUDES="-Iincludes -I../../qfe_mod/include -I/usr/local/cuda-12.6/include/ $H5I"
LDFLAGS="-L/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/cuda/12.3/targets/x86_64-linux/lib/ -L/mnt/hdd_barracuda/opt/myhdfstuff/hdf5-2.1.0/lib/ -L/usr/lib/ -L/usr/local/lib/ -lhdf5 -lgsl -lgslcblas -lm"
export LD_LIBRARY_PATH=/mnt/hdd_barracuda/opt/myhdfstuff/hdf5-2.1.0/lib:${LD_LIBRARY_PATH:-}
SRC=distill_peram_mrhs_claude.cu
BIN="distill_peram_mrhs_L${L}_claude.o"

# ---- build if source newer than binary (the --out-suffix flag was just added) ----
if [ ! -f "$BIN" ] || find . -maxdepth 2 \( -name '*.cu' -o -name '*.h' \) -newer "$BIN" -print -quit 2>/dev/null | grep -q .
then
  echo "### compile mrhs L${L} -> $BIN  [$(date +%F_%H:%M:%S)] ###"
  "$NVCC" "$SRC" $NVCCFLAGS $INCLUDES $LDFLAGS -o "$BIN" \
    || { echo "### mrhs L${L} BUILD FAILED ###"; exit 1; }
else
  echo "### mrhs L${L} binary up-to-date ###"
fi

# ---- MPS daemon (2-pack) ----
if ! pgrep -f nvidia-cuda-mps-control >/dev/null
then
  echo "### starting MPS daemon ###"
  nvidia-cuda-mps-control -d
  for i in 1 2 3 4 5; do pgrep -f nvidia-cuda-mps-control >/dev/null && break; sleep 1; done
fi
pgrep -f nvidia-cuda-mps-control >/dev/null || { echo "### ERROR: MPS daemon failed ###"; exit 1; }

# ---- collect ensembles ----
ENS=()
for d in $ENS_GLOB
do
  [ -d "$d" ] || continue
  ls "$d"/ckpoint_lat.* >/dev/null 2>&1 || continue
  ENS+=( "$d" )
done
echo "### ${#ENS[@]} L${L} ensembles matched (${AT_TOKEN}); skip-protected -> only missing configs generated ###"
printf '  %s\n' "${ENS[@]}"

run_worker () {   # $1=WID
  local WID="$1"
  local stride_eff=$(( STRIDE * NPACK ))
  local LOG="distill_L${L}_mrhs_w${WID}_claude.log"
  local ens nf gsq at first last kmin_w kmax
  {
    echo "### START mrhs sweep L${L} worker ${WID}/${NPACK}  GPU${GPU}  stride_eff=${stride_eff}  Nv=${NV}  [$(date +%F_%H:%M:%S)] ###"
    for ens in "${ENS[@]}"
    do
      nf=$(printf '%s' "$ens" | grep -oE 'Nf[0-9]+' | head -1 | sed 's/Nf//')
      gsq=$(printf '%s' "$ens" | grep -oE 'gsq[0-9.]+at' | sed 's/gsq//;s/at//')
      at=$(printf '%s' "$ens" | grep -oE 'at[0-9.]+nu0' | sed 's/at//;s/nu0//')
      first=$(ls "$ens"/ckpoint_lat.* 2>/dev/null | sed 's#.*ckpoint_lat\.##' | grep -E '^[0-9]+$' | sort -n | head -1)
      last=$( ls "$ens"/ckpoint_lat.* 2>/dev/null | sed 's#.*ckpoint_lat\.##' | grep -E '^[0-9]+$' | sort -n | tail -1)
      [ -z "$first" ] && { echo "### SKIP $ens (no ckpoint_lat) ###"; continue; }
      kmin_w=$(( first + STRIDE * WID ))
      kmax=$(( last + 1 ))
      [ "$kmin_w" -ge "$kmax" ] && { echo "### SKIP $ens w${WID} (kmin>=kmax) ###"; continue; }
      echo "### $ens  Nf${nf} g${gsq} at${at}  kmin=${kmin_w} stride=${stride_eff} kmax=${kmax}  [$(date +%F_%H:%M:%S)] ###"
      CUDA_VISIBLE_DEVICES=$GPU ./"$BIN" --gsq "$gsq" --Nf "$nf" --nu0 1.0 --at "$at" \
        --nv "$NV" --tsrc0 "$TSRC0" --twin "$TWIN" --nsrc 1 --out-suffix "" \
        --ens-dir "$ens/" --kmin "$kmin_w" --stride "$stride_eff" --kmax "$kmax"
      echo "### $ens w${WID} done (status $?)  [$(date +%F_%H:%M:%S)] ###"
    done
    echo "### mrhs sweep L${L} worker ${WID} ALL DONE  [$(date +%F_%H:%M:%S)] ###"
  } >> "$LOG" 2>&1
}

echo "### START mrhs sweep L${L}: GPU${GPU} x MPS ${NPACK}-pack, --nsrc 1 --out-suffix '' (merge into distill_Nv24/)  [$(date +%F_%H:%M:%S)] ###"
for (( w=0; w<NPACK; w++ )); do run_worker "$w" & done
wait
echo "### ALL WORKERS DONE  [$(date +%F_%H:%M:%S)] ###"
