#!/usr/bin/env bash
# tmp_peram_mrhs_validate_claude.sh
#   Build (if absent) + VALIDATE the mrhs / multi-source perambulator driver distill_peram_mrhs_claude.cu.
#   Writes perams to data_<ens>/distill_Nv24_v2/  (SEPARATE _v2 dir -- NEVER touches the existing distill_Nv24/).
#   Validation is self-contained (T2a/T2b/T2c reconstruction vs a direct D_ov^{-1} apply) + per-window wall-time.
#   Run this ONLY after the _v1 distill run is stopped (frees the GPU); the _v1 run is resumable (skips any
#   config whose h5 already has /peram/tau).  NO rm / NO kill anywhere.
#
#   Ensemble = Nf6 gsq1.0 L1 (the active-run ensemble); configs k=1 (--nsrc 1) and k=21 (--nsrc 2), already
#   generated by _v1 so the gauge configs are present.  Compare the mrhs per-config time to the _v1 ~450 s/config.
set -u
cd /mnt/barracuda22/qed3/qed3/src/production || exit 1
export OMP_NUM_THREADS=8
GPU="${GPU:-1}"                                   # distill L1 ran on GPU1; override with GPU=... if needed
export CUDA_VISIBLE_DEVICES="$GPU"

BIN=distill_peram_mrhs_L1_claude.o
SRC=distill_peram_mrhs_claude.cu
NVCC=/usr/local/cuda-12.6/bin/nvcc
NVCCFLAGS="-w -arch=sm_70 -O2 -std=c++20 -lcublas -lcusolver -lcusparse -lgomp -Xcompiler -fopenmp"
H5I="-I/mnt/hdd_barracuda/opt/highfive/include/ -I/mnt/hdd_barracuda/opt/myhdfstuff/hdf5-2.1.0/include/"
INCLUDES="-Iincludes -I../../qfe_mod/include -I/usr/local/cuda-12.6/include/ $H5I"
LDFLAGS="-L/opt/nvidia/hpc_sdk/Linux_x86_64/24.3/cuda/12.3/targets/x86_64-linux/lib/ -L/mnt/hdd_barracuda/opt/myhdfstuff/hdf5-2.1.0/lib/ -L/usr/lib/ -L/usr/local/lib/ -lhdf5 -lgsl -lgslcblas -lm"
export LD_LIBRARY_PATH=/mnt/hdd_barracuda/opt/myhdfstuff/hdf5-2.1.0/lib:${LD_LIBRARY_PATH:-}

LOG=tmp_peram_mrhs_validate_claude.log
ENS=Nf6_gsq1.000000at0.200000nu01.000000mRe0.000000mIm0.000000nt128L1_hb1.000000
COMMON="--gsq 1.000000 --Nf 6 --nu0 1.0 --at 0.200000 --nv 24 --tsrc0 0 --twin 32 --ens-dir ${ENS}/"

echo "================ peram-mrhs VALIDATE START $(date) ================" | tee "$LOG"
echo "---- GPU=$GPU  ens=$ENS ----" | tee -a "$LOG"

# ---- build if absent ----
if [ ! -x "$BIN" ]
then
  echo "---- building $BIN ----" | tee -a "$LOG"
  T0=$(date +%s)
  "$NVCC" "$SRC" $NVCCFLAGS $INCLUDES $LDFLAGS -o "$BIN" 2>&1 | tee -a "$LOG"
  RC="${PIPESTATUS[0]}"
  T1=$(date +%s)
  if [ "$RC" -ne 0 ]
  then
    echo "BUILD FAILED (rc=$RC) after $((T1-T0)) s -- stopping." | tee -a "$LOG"
    exit 1
  fi
  echo "build OK in $((T1-T0)) s -> $BIN" | tee -a "$LOG"
else
  echo "---- $BIN already built, skipping compile ----" | tee -a "$LOG"
fi

# ---- PHASE 1: correctness + single-window speedup (--nsrc 1, k=1) ----
echo "---- PHASE 1: correctness + timing  --nsrc 1  k=1  $(date) ----" | tee -a "$LOG"
./"$BIN" $COMMON --nsrc 1 --kmin 1 --stride 20 --kmax 2 2>&1 | tee -a "$LOG"
echo "  [phase1 rc=${PIPESTATUS[0]}]" | tee -a "$LOG"

# ---- PHASE 2: second source window layout (--nsrc 2 -> {0,64}, k=21) ----
echo "---- PHASE 2: multi-source  --nsrc 2  k=21  $(date) ----" | tee -a "$LOG"
./"$BIN" $COMMON --nsrc 2 --kmin 21 --stride 20 --kmax 22 2>&1 | tee -a "$LOG"
echo "  [phase2 rc=${PIPESTATUS[0]}]" | tee -a "$LOG"

echo "---- output h5 written (separate _v2 dir) ----" | tee -a "$LOG"
ls -l "data_${ENS}/distill_Nv24_v2/" 2>&1 | tee -a "$LOG"
echo "================ peram-mrhs VALIDATE DONE $(date) ================" | tee -a "$LOG"
echo "PASS CRITERIA: T2a/T2b/T2c ~ solver tol (1e-5..1e-6);  per-window mrhs time << _v1 ~450 s/config."
