#pragma once

// wilson_shapes_claude.h
//
// GENERIC spatial Wilson-loop shapes for the enlarged glueball operator basis.
//
// A shape INSTANCE = { faces[i] with a relative-orientation weight w[i] in {+1,-1},
//                      an insertion point r_ins (unit VE) = the Y_lm evaluation point }.
// Holonomy (gauge-invariant):
//   theta_inst(s) = sum_i w[i] * face_sign[faces[i]] * plaquette_angle(s, face_i).
// face_sign gives the physical (outward-CCW) flux Phi(f); w[i] is the shape's intrinsic traversal
// choice. Two-triangle shapes come UNTWISTED w=(+,+) (Phi0+Phi1) and TWISTED w=(+,-) (Phi0-Phi1):
//   rect / twisted rect      = edge-sharing pair (untwisted: shared edge cancels = rectangle loop),
//   figure-8 / twisted fig-8 = vertex-sharing pair (no edge cancels).
// The linear operator (Phi0 +- Phi1) is parity-ODD -> ok for the linear F_12 study; squared for F^2.
//
// A shape is defined by a base instance; its icosahedral ORBIT is generated by applying the 120 Ih
// elements (faces via the site-orbit table, r_ins via the group matrix; weights ride along). Each
// orbit -> one operator per (ell,em):
//   O(s) = (1/N) sum_{inst in orbit} Ylm(inst.r_ins) * g( theta_inst(s) ),   g = theta or theta^2.
// Instances are canonicalized (sort faces, fix global sign w[0]=+1) so +-holonomy dedupe.
//
// Adding a shape = provide an enumerator of base instances. Include AFTER s2n_simp.h, valence.h
// (Ylm_real), gauge_ext.h, icos_orbits_claude.h.

#include <vector>
#include <array>
#include <set>
#include <map>
#include <utility>
#include <algorithm>

template<class Base>
struct WilsonShapes {
  using Link = typename Base::Link;
  static constexpr int NIh = IcosOrbits<Base>::NIh;

  struct Instance {
    std::vector<Idx> faces;
    std::vector<int> w;       // relative orientation +-1, aligned with faces
    VE r_ins;                 // insertion / Y_lm evaluation point (unit)
  };

  const Base& base;
  const IcosOrbits<Base>& orb;
  std::map<std::array<Idx,3>, Idx> face_key;   // sorted vertex triple -> face index
  bool use_face_sign = true;   // false -> raw plaquette_angle (matches density plaquette_angle_avg_Ylm_real)

  WilsonShapes(const Base& base_, const IcosOrbits<Base>& orb_)
    : base(base_), orb(orb_)
  {
    for(Idx f=0; f<base.n_faces; f++){
      const auto& fc = base.faces[f];
      std::array<Idx,3> t{fc[0],fc[1],fc[2]};
      std::sort(t.begin(), t.end());
      face_key[t] = f;
    }
  }

  // canonical key: (face,weight) pairs sorted by face, global sign fixed so first weight = +1
  std::vector<std::pair<Idx,int>> key(const Instance& in) const {
    std::vector<std::pair<Idx,int>> p;
    for(size_t i=0; i<in.faces.size(); i++) p.push_back({in.faces[i], in.w[i]});
    std::sort(p.begin(), p.end());
    if(!p.empty() && p[0].second < 0) for(auto& e : p) e.second = -e.second;
    return p;
  }

  Idx map_face(const Idx f, const int ig) const {
    const auto& fc = base.faces[f];
    std::array<Idx,3> t{ orb.orbits[fc[0]][ig], orb.orbits[fc[1]][ig], orb.orbits[fc[2]][ig] };
    std::sort(t.begin(), t.end());
    return face_key.at(t);
  }

  Instance map_instance(const Instance& in, const int ig) const {
    Instance out;
    out.faces.reserve(in.faces.size());
    for(const Idx f : in.faces) out.faces.push_back( map_face(f, ig) );
    out.w = in.w;   // faces + weights stay PAIRED in the same order (do NOT sort faces alone --
                    // that would detach the twist sign). holonomy is order-independent; key() sorts
                    // (face,weight) pairs together for canonical dedup.
    out.r_ins = (orb.group[ig] * in.r_ins).normalized();// insertion point rotates with the group
    // ^ RE-NORMALIZE: group matrices carry ~1e-13 orthogonality error (esp. under nvcc), so a
    //   rotated near-pole vertex can get r_z = 1+eps > 1 -> Ylm_real's acos(r_z) = NaN. Fixed here.
    return out;
  }

  std::vector<Instance> orbit_of(const Instance& base_in) const {
    std::set<std::vector<std::pair<Idx,int>>> seen;
    std::vector<Instance> out;
    for(int ig=0; ig<NIh; ig++){
      Instance im = map_instance(base_in, ig);
      if(seen.insert(key(im)).second) out.push_back(im);
    }
    return out;
  }

  std::vector<std::vector<Instance>> orbits_from(const std::vector<Instance>& cands) const {
    std::set<std::vector<std::pair<Idx,int>>> seen;
    std::vector<std::vector<Instance>> out;
    for(const Instance& c : cands){
      if(seen.count(key(c))) continue;
      std::vector<Instance> orbit = orbit_of(c);
      for(const Instance& o : orbit) seen.insert(key(o));
      out.push_back(orbit);
    }
    return out;
  }

  // --- shape enumerators (base instances) ---
  // single triangle
  std::vector<Instance> triangles() const {
    std::vector<Instance> v;
    for(Idx f=0; f<base.n_faces; f++)
      v.push_back( Instance{ {f}, {+1}, base.dual_sites[f] } );
    return v;
  }

  // two-triangle shape: edge-sharing (rect) or vertex-sharing (figure-8); sigma = relative twist
  std::vector<Instance> two_triangle(const bool edge, const int sigma) const {
    std::vector<Instance> v;
    if(edge){
      for(Idx il=0; il<base.n_links; il++){
        Instance in;
        in.faces = { base.dual_links[il][0], base.dual_links[il][1] };
        in.w = { +1, sigma };
        in.r_ins = ( base.sites[ base.links[il][0] ] + base.sites[ base.links[il][1] ] ).normalized();
        v.push_back(in);
      }
    } else {
      for(Idx f0=0; f0<base.n_faces; f0++){
        for(Idx f1=f0+1; f1<base.n_faces; f1++){
          Idx shared=-1;
          int cnt=0;
          for(const Idx a : base.faces[f0])
            for(const Idx b : base.faces[f1])
              if(a==b){ shared=a; cnt++; }
          if(cnt!=1) continue;   // 2 shared = edge (rect); 0 = disjoint
          Instance in;
          in.faces = { f0, f1 };
          in.w = { +1, sigma };
          in.r_ins = base.sites[shared];
          v.push_back(in);
        }
      }
    }
    return v;
  }
  std::vector<Instance> rectangles()          const { return two_triangle(true,  +1); }
  std::vector<Instance> twisted_rectangles()  const { return two_triangle(true,  -1); }
  std::vector<Instance> figure8s()            const { return two_triangle(false, +1); }
  std::vector<Instance> twisted_figure8s()    const { return two_triangle(false, -1); }

  // three-triangle shape: a CENTRAL face f0 plus two of its three edge-neighbors (so f0 shares two
  // of its links with the two neighbors). With w=(+,+,+) the two shared links cancel -> a single
  // larger boundary loop. r_ins = centroid of the central triangle. At L=1 this is ONE Ih orbit;
  // at higher L there are several inequivalent placements (multiple orbits -> needs more care).
  std::vector<Instance> three_triangles() const {
    // face neighbors across each edge, from the link->(face,face) adjacency
    std::vector<std::vector<Idx>> fnbr(base.n_faces);
    for(Idx il=0; il<base.n_links; il++){
      fnbr[ base.dual_links[il][0] ].push_back( base.dual_links[il][1] );
      fnbr[ base.dual_links[il][1] ].push_back( base.dual_links[il][0] );
    }
    std::vector<Instance> v;
    for(Idx f0=0; f0<base.n_faces; f0++){
      const std::vector<Idx>& nb = fnbr[f0];
      for(size_t i=0; i<nb.size(); i++){
        for(size_t j=i+1; j<nb.size(); j++){
          Instance in;
          in.faces = { f0, nb[i], nb[j] };
          in.w = { +1, +1, +1 };
          in.r_ins = base.dual_sites[f0];   // centroid of the central triangle
          v.push_back(in);
        }
      }
    }
    return v;
  }

  // four-triangle STAR shape: a CENTRAL face f0 plus ALL 3 of its edge-neighbors (so f0 shares each
  // of its 3 links with one neighbor). w=(+,+,+,+) -> total oriented flux through the 4-triangle patch.
  // r_ins = centroid of the central triangle. On a closed simplicial sphere every face has exactly 3
  // edge-neighbors; at L=1 this is ONE Ih orbit, at higher L several inequivalent placements (orbits).
  std::vector<Instance> four_triangles() const {
    std::vector<std::vector<Idx>> fnbr(base.n_faces);
    for(Idx il=0; il<base.n_links; il++){
      fnbr[ base.dual_links[il][0] ].push_back( base.dual_links[il][1] );
      fnbr[ base.dual_links[il][1] ].push_back( base.dual_links[il][0] );
    }
    std::vector<Instance> v;
    for(Idx f0=0; f0<base.n_faces; f0++){
      const std::vector<Idx>& nb = fnbr[f0];
      if(nb.size() != 3) continue;                 // interior triangle with all 3 edge-neighbors
      Instance in;
      in.faces = { f0, nb[0], nb[1], nb[2] };
      in.w = { +1, +1, +1, +1 };
      in.r_ins = base.dual_sites[f0];              // centroid of the central triangle
      v.push_back(in);
    }
    return v;
  }

  // TRIO shape: the STAR without its middle triangle -- the 3 edge-neighbors of a central face f0
  // (f0 itself dropped), w=(+,+,+), still centered on f0 (r_ins = dual_sites[f0]). = star - center.
  std::vector<Instance> trios() const {
    std::vector<std::vector<Idx>> fnbr(base.n_faces);
    for(Idx il=0; il<base.n_links; il++){
      fnbr[ base.dual_links[il][0] ].push_back( base.dual_links[il][1] );
      fnbr[ base.dual_links[il][1] ].push_back( base.dual_links[il][0] );
    }
    std::vector<Instance> v;
    for(Idx f0=0; f0<base.n_faces; f0++){
      const std::vector<Idx>& nb = fnbr[f0];
      if(nb.size() != 3) continue;
      Instance in;
      in.faces = { nb[0], nb[1], nb[2] };          // 3 edge-neighbors only (central f0 removed)
      in.w = { +1, +1, +1 };
      in.r_ins = base.dual_sites[f0];              // still centered on the removed central face
      v.push_back(in);
    }
    return v;
  }

  // FIVE-SIX shape: the contour around each SITE -- the 5 or 6 faces meeting at vertex s (5 at the 12
  // icosahedron vertices, 6 elsewhere), w=+1 each -> total oriented flux through the pentagon/hexagon
  // patch. r_ins = site position. Pentagons and hexagons fall in different Ih orbits (consolidated).
  std::vector<Instance> site_contours() const {
    std::vector<std::vector<Idx>> site_faces(base.n_sites);
    for(Idx f=0; f<base.n_faces; f++){
      for(const Idx s : base.faces[f]) site_faces[s].push_back(f);
    }
    std::vector<Instance> v;
    for(Idx s=0; s<base.n_sites; s++){
      const std::vector<Idx>& fs = site_faces[s];
      if(fs.empty()) continue;
      Instance in;
      in.faces.assign(fs.begin(), fs.end());
      in.w.assign((int)fs.size(), +1);
      in.r_ins = base.sites[s];                    // site position (unit)
      v.push_back(in);
    }
    return v;
  }

  // --- generic holonomy / operator ---
  template<typename Gauge>
  double holonomy(const Gauge& U, const int s, const Instance& in) const {
    double th = 0.0;
    for(size_t i=0; i<in.faces.size(); i++){
      const Idx f = in.faces[i];
      const int fs = use_face_sign ? base.face_signs[f] : 1;   // toggle: consistent-outward vs raw orientation
      th += in.w[i] * fs * U.plaquette_angle(s, base.faces[f]);
    }
    return th;
  }

  template<typename Gauge>
  double op(const Gauge& U, const int s, const std::vector<Instance>& orbit,
            const int ell, const int em, const bool squared) const {
    double avg = 0.0;
    for(const Instance& in : orbit){
      const double th = holonomy(U, s, in);
      const double g = squared ? th*th : th;
      avg += Ylm_real(ell, em, in.r_ins) * g;
    }
    return avg / orbit.size();
  }
};
